
#define CK_MAJOR_VERSION @VERSION_MAJOR@
#define CK_MINOR_VERSION @VERSION_MINOR@
#define CK_PATCH_VERSION @VERSION_PATCH@
#define CK_COMMIT_VERSION "@VERSION_COMMIT@"
#define CK_REVISION_VERSION @VERSION_REVISION@

#define CK_VERSION_FULL "@VERSION_FULL@"
#define CK_VERSION "@VERSION@"




