
#define CK_MAJOR_VERSION 0
#define CK_MINOR_VERSION 0
#define CK_PATCH_VERSION 2
#define CK_COMMIT_VERSION "g6de35c9"
#define CK_REVISION_VERSION 10

#define CK_VERSION_FULL "0.0.2.1.cg6de35c9.r10"
#define CK_VERSION "0.0.2.1"




