
#define CK_MAJOR_VERSION 0
#define CK_MINOR_VERSION 0
#define CK_PATCH_VERSION 2
#define CK_COMMIT_VERSION "g59a1c92"
#define CK_REVISION_VERSION 9

#define CK_VERSION_FULL "0.0.2.0.cg59a1c92.r9"
#define CK_VERSION "0.0.2.0"




